/*
 * File: app/view/project/Edit.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */
 
Ext.define('BO.view.project.Edit', {
    extend: 'Ext.window.Window',
    alias: 'widget.projectedit',
	requires:[
		'Ext.form.field.Date',
		'Ext.form.field.Checkbox',
		'BO.lib.components.uploadCustomButton',
		'Ext.form.field.Hidden'
	],
    autoShow: false,
	closeAction:'hide',
    width: 460,
    resizable: false,
	modal:true,
    title: 'Proyecto',

    initComponent: function() {
        var me = this;

		var catStore = Ext.create('BO.store.Default',{model: 'BO.model.Category'});
		
		
        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    border: 0,
                    width: '100%',
					minHeight:570,
					bodyPadding: 4,
                    items: [{
                        
						xtype:'tabpanel',
						plain:true,
						items: [{
							title: 'Principal',
							defaults: {
								labelAlign: 'top',
								msgTarget: 'side',
								width: '100%'
							},
							bodyPadding: 10,
							items:[
								{
									xtype:'hiddenfield',
									name:'proyecto_id'
								},
								{
									xtype: 'textfield',
									name: 'proyecto_titulo',
									fieldLabel: 'Título*',
									allowBlank: false
								},
								{
									xtype: 'datefield',
									fieldLabel: 'Fecha',
									name:'proyecto_fecha',
									format: "d/m/Y",
									allowBlank:false,
									editable: false,
									enableKeyEvents: true,
									listeners: {
										keydown: function (combo, e){
											e.stopEvent();
										}
									}
								},{
									xtype:'uploadcustombutton',
									url:'index.php?controller=proyecto&action=upload',
									name:'proyecto_ficha',
									glyph:0xf07c,
									text:'Seleccionar Ficha...'
								},{
									xtype: 'checkboxfield',
									fieldLabel: 'Publicado',
									boxLabel: 'Si',
									name:'proyecto_publicada',
									uncheckedValue: 0
								},{
									xtype: 'remotecombobox',
									name:'proyecto_categoria_id',
									displayField: 'categoria_nombre',
									valueField: 'categoria_id',
									store: catStore,
									fieldLabel: 'Categoria'
								},
								{
									xtype: 'textarea',
									height: 216,
									width: '100%',
									fieldLabel: 'Texto',
									name:'proyecto_cuerpo',
									enableFont:false,
									enableFontSize:false,
									enableColors:false
								}
							]
						},{
							title:'Imágenes',
							itemId:'tabImagenes',
							cls:'tabImages',
							items:[{						
								xtype:'dataview',
								store:'',
								height:450,
								tpl: [
									'<tpl for=".">',
										'<div class="thumb-wrap" id="{foto_id}">',
											'<div class="thumb"><img src="'+CONFIG.UrlDocumentos+'{foto_imagen}"></div>',
										'</div>',
									'</tpl>'
								],
								trackOver: true,
								overItemCls: 'x-item-over',
								itemSelector: 'div.thumb-wrap',
								emptyText: 'No hay imágenes que mostrar'
							},{						
								xtype:'toolbar',
								items:[{
									xtype:'uploadcustombutton',
									glyph:0xf07c,
									url:'index.php?controller=foto&action=upload',
									action:'addimage'
								},{
									xtype:'button',
									text: 'Eliminar',
									action:'delete',
									glyph:0xf014,
									disabled:true
								}]						
							}]
						}]
                    }],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            items: [
                                {
                                    xtype: 'component',
                                    flex: 1
                                },
                                {
                                    xtype: 'button',
                                    action: 'save',
                                    text: 'Aceptar',
                                    formBind: true
                                },
                                {
                                    xtype: 'button',
                                    action: 'cancel',
                                    text: 'Cancelar'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});