/*
 * File: app/view/myviewport.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BO.view.myviewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.myviewport',
	requires: [
		'Ext.layout.container.Border',
		'Ext.layout.container.Card',
		'Ext.tab.*'	
	],
    itemId: 'myViewport',
    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    itemId: 'panelMain',
                    padding: '8 0 0 0',
                    activeTab: 0,
                    region: 'center'
                },
                {
                    xtype: 'toolbar',
                    itemId: 'toolbarMain',
					cls: 'app-header',
                    region: 'north'
                }
            ]
        });

        me.callParent(arguments);
    }

});